\input texinfo
@c -----------------------------------------------------------------------------
@c File     : kmaxima.texi
@c License  : GNU General Public License (GPL)
@c Language : German
@c Author   : Dr. Dieter Kaiser
@c Date     : 05.03.2011
@c Revision : 08.11.2011
@c 
@c Copyright (C) 2011 by Dr. Dieter Kaiser
@c -----------------------------------------------------------------------------

@ifnottex
@documentencoding ISO-8859-1
@end ifnottex

@afourpaper

@paragraphindent 0
@exampleindent 0
@include macros.texi

@setfilename maxima.info
@synindex vr fn

@settitle Maxima intern

@setchapternewpage odd
@ifinfo
Das ist ein Texinfo Maxima Manual

Copyright 2011 by Dr. Dieter Kaiser

@format
START-INFO-DIR-ENTRY
* Maxima: (maxima).     Ein Computer Algebra System.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@titlepage
@sp 10
@center @titlefont{Aufbau und Programmierung}
@sp 1
@center @titlefont{des Computeralgebrasystem}
@sp 1
@center @titlefont{Maxima}
@sp 1
@center Version 1.0
@page
@vskip 0pt plus 1filll

@end titlepage

@summarycontents
@contents

@ifnottex
@node Top, Grundger@"ust, (dir), (dir)
@top
@end ifnottex

@menu
* Einf@"uhrung::
* Grundger@"ust::
* Erste Makros und Hilfsfunktionen::
* Parser::
* Lineare Anzeige::
* 2D-Anzeige::
* Systemfunktionen::
* Vereinfachung::
* Grosse Gleitkommazahlen::
* Dateieingabe und -ausgabe::
* kmaxima.lisp::
* Quelltext::
* Index der Funktionen und Variablen::
@end menu

@node Einf@"uhrung, Grundger@"ust, Top, Top
@chapter Einf@"uhrung
@include Einfuehrung.texi

@node Grundger@"ust, Erste Makros und Hilfsfunktionen, Einf@"uhrung, Top
@chapter Grundger@"ust
@include Grundgeruest.texi

@node Erste Makros und Hilfsfunktionen, Parser, Grundger@"ust, Top
@chapter Erste Makros und Hilfsfunktionen
@include Hilfsfunktionen.texi

@node Parser, Lineare Anzeige, Erste Makros und Hilfsfunktionen, Top
@chapter Parser
@include Parser.texi

@node Lineare Anzeige, 2D-Anzeige, Parser, Top
@chapter Lineare Anzeige
@include LDisplay.texi

@node 2D-Anzeige, Systemfunktionen, Lineare Anzeige, Top
@chapter 2D-Anzeige
@include 2DDisplay.texi

@node Systemfunktionen, Vereinfachung, 2D-Anzeige, Top
@chapter Systemfunktionen
@include Systemfunktionen.texi

@node Vereinfachung, Grosse Gleitkommazahlen, Systemfunktionen, Top
@chapter Vereinfachung
@include Vereinfachung.texi

@node Grosse Gleitkommazahlen, Dateieingabe und -ausgabe, Vereinfachung, Top
@chapter Gro@ss{}e Gleitkommazahlen
@include Bigfloat.texi

@node Dateieingabe und -ausgabe, kmaxima.lisp, Vereinfachung, Top
@chapter Dateieingabe und -ausgabe
@include Dateien.texi

@node kmaxima.lisp, Quelltext, Dateieingabe und -ausgabe, Top
@appendix kmaxima.lisp
@include Quelltext1.texi

@node Quelltext, Index der Funktionen und Variablen, kmaxima.lisp, Top
@appendix Quelltext
@include Quelltext2.texi

@node Index der Funktionen und Variablen, , Quelltext, Top
@appendix Index der Funktionen und Variablen
@printindex fn

@bye

@c --- End of file kmaxima.texi ------------------------------------------------

